baseurl = "/"
languageCode = "be-nl"
title = "GS Sukarti"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "stage"
    name = "Stages"
    title = "stage"
    url = "/pages/stage/"
    weight = -100

  [[menu.main]]
    identifier = "trainingsuren"
    name = "Trainingsuren"
    title = "trainingsuren"
    url = "/pages/uren/"
    weight = -90

  [[menu.main]]
    identifier = "lidgeld"
    name = "Lidgeld"
    title = "lidgeld"
    url = "/pages/lidgeld/"
    weight = -70

[[menu.main]]
    identifier = "sponsors"
    name = "Sponsors"
    title = "sponsors"
    url = "/sponsors/"
    weight = -70
