backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "sponsors"
    label: "Sponsor"
    folder: "data/sponsors/"
    extension: json
    create: true
    slug: {{slug}}
    fields:
      - {label: "Sponsor", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Weight", name: "weight", widget: "number", default: 50}
      - {label: "Ondertitel", name: "subtitle", widget: "string", required: false}
  - name: "pages"
    label: "Pages"
    create: true
    files:
      - file: "site/content/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/stage/index.md"
        label: "Stage"
        name: "stage"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
